spring:
    profiles: test
    datasource:
      username: username
      password: password
      url: 'jdbc:mysql://192.168.2.215:3206/dbname?characterEncoding=utf8&amp;allowMultiQueries=true'
      driver-class-name: com.mysql.jdbc.Driver
