spring:
    profiles: bug
    datasource:
      username: username
      password: password
      url: 'jdbc:mysql://192.168.2.209:3806/dbname?characterEncoding=utf8&amp;allowMultiQueries=true'
      driver-class-name: com.mysql.jdbc.Driver
logging:
  level: debug
server:
  error:
    whitelabel:
      enabled: true
